package com.wawra.stations.logic

import java.util.*

fun String.fix() = this.toUpperCase(Locale.getDefault())
    .replace('Ą', 'A')
    .replace('Á', 'A')
    .replace('Ć', 'C')
    .replace('Č', 'C')
    .replace('É', 'E')
    .replace('Ę', 'E')
    .replace('Ě', 'E')
    .replace('Í', 'I')
    .replace('Ľ', 'L')
    .replace('Ł', 'L')
    .replace('Ń', 'N')
    .replace('Ň', 'N')
    .replace('Ö', 'O')
    .replace('Ó', 'O')
    .replace('Ř', 'R')
    .replace('Ś', 'S')
    .replace('Š', 'S')
    .replace('Ú', 'U')
    .replace('Ü', 'U')
    .replace('Ů', 'U')
    .replace('Ý', 'Y')
    .replace('Ż', 'Z')
    .replace('Ź', 'Z')
    .replace('Ž', 'Z')